from csbot.slackbot.utils import ParsedIssueOrPRBody, format_attribution, parse_issue_or_pr_body


class TestParseIssueBody:
    """Test suite for parse_issue_or_pr_body function."""

    def test_empty_body(self):
        """Test parsing an empty body."""
        result = parse_issue_or_pr_body("")
        expected = ParsedIssueOrPRBody(
            cleaned_body="",
            opened_by=None,
            slack_message_url=None,
            created_date=None,
        )
        assert result == expected

    def test_none_body(self):
        """Test parsing a None body (falsy value)."""
        result = parse_issue_or_pr_body("")
        expected = ParsedIssueOrPRBody(
            cleaned_body="",
            opened_by=None,
            slack_message_url=None,
            created_date=None,
        )
        assert result == expected

    def test_body_without_attribution(self):
        """Test parsing a body without any attribution line."""
        body = """# Data Request

This is a regular data request without attribution.

## Details

Some more content here."""

        result = parse_issue_or_pr_body(body)
        expected = ParsedIssueOrPRBody(
            cleaned_body=body.strip(),
            opened_by=None,
            slack_message_url=None,
            created_date=None,
        )
        assert result == expected

    def test_attribution_with_slack_link(self):
        """Test parsing attribution with a Slack message link as generated by the GitHub API utilities."""
        attribution = format_attribution(
            "Created",
            "John Doe",
            "2024-01-15 10:30:00 UTC",
            "https://slack.com/archives/C123456/p1705314600",
        )
        body = f"""{attribution}

# Data Request Title

This is the actual content of the data request.

## Analysis Required

- Item 1
- Item 2"""

        result = parse_issue_or_pr_body(body)
        expected = ParsedIssueOrPRBody(
            cleaned_body="""This is the actual content of the data request.

## Analysis Required

- Item 1
- Item 2""",
            opened_by="John Doe",
            slack_message_url="https://slack.com/archives/C123456/p1705314600",
            created_date="2024-01-15 10:30:00 UTC",
        )
        assert result == expected

    def test_attribution_without_slack_link(self):
        """Test parsing attribution without a Slack link."""
        attribution = format_attribution("Created", "Jane Smith", "2024-02-20 15:45:30 UTC")
        body = f"""{attribution}

# Analysis Request

Need help with this dataset."""

        result = parse_issue_or_pr_body(body)
        expected = ParsedIssueOrPRBody(
            cleaned_body="Need help with this dataset.",
            opened_by="Jane Smith",
            slack_message_url=None,
            created_date="2024-02-20 15:45:30 UTC",
        )
        assert result == expected

    def test_attribution_with_markdown_formatted_name(self):
        """Test parsing attribution where the name contains markdown formatting."""
        # The bot doesn't typically create markdown-formatted names, but users might edit them
        attribution = format_attribution(
            "Created",
            "**Alice Johnson**",
            "2024-03-10 09:15:22 UTC",
            "https://example.slack.com/archives/ABC123/p1710059722",
        )
        body = f"""{attribution}

# Request Details

Data analysis needed."""

        result = parse_issue_or_pr_body(body)
        expected = ParsedIssueOrPRBody(
            cleaned_body="Data analysis needed.",
            opened_by="Alice Johnson",  # The ** should be stripped by strip("*")
            slack_message_url="https://example.slack.com/archives/ABC123/p1710059722",
            created_date="2024-03-10 09:15:22 UTC",
        )
        assert result == expected

    def test_attribution_with_header_separator(self):
        """Test that headers after attribution are properly skipped."""
        attribution = format_attribution(
            "Created", "Bob Wilson", "2024-04-05 12:00:00 UTC", "https://slack.com/test"
        )
        body = f"""{attribution}

---

Some content that should remain."""

        result = parse_issue_or_pr_body(body)
        expected = ParsedIssueOrPRBody(
            cleaned_body="Some content that should remain.",
            opened_by="Bob Wilson",
            slack_message_url="https://slack.com/test",
            created_date="2024-04-05 12:00:00 UTC",
        )
        assert result == expected

    def test_attribution_with_hash_header(self):
        """Test that hash headers after attribution are properly skipped."""
        attribution = format_attribution("Created", "Carol Davis", "2024-05-01 08:30:15 UTC")
        body = f"""{attribution}

# Main Header

Content under the header."""

        result = parse_issue_or_pr_body(body)
        expected = ParsedIssueOrPRBody(
            cleaned_body="Content under the header.",
            opened_by="Carol Davis",
            slack_message_url=None,
            created_date="2024-05-01 08:30:15 UTC",
        )
        assert result == expected

    def test_attribution_with_empty_lines_after(self):
        """Test handling of empty lines after attribution."""
        attribution = format_attribution(
            "Created",
            "Dave Miller",
            "2024-06-15 14:20:10 UTC",
            "https://company.slack.com/archives/GENERAL/p1718462410",
        )
        body = f"""{attribution}



# Data Analysis

Actual content starts here."""

        result = parse_issue_or_pr_body(body)
        expected = ParsedIssueOrPRBody(
            cleaned_body="Actual content starts here.",
            opened_by="Dave Miller",
            slack_message_url="https://company.slack.com/archives/GENERAL/p1718462410",
            created_date="2024-06-15 14:20:10 UTC",
        )
        assert result == expected

    def test_multiple_attribution_lines_only_first_parsed(self):
        """Test that only the first attribution line is parsed."""
        first_attribution = format_attribution(
            "Created", "First User", "2024-07-01 10:00:00 UTC", "https://slack.com/first"
        )
        second_attribution = format_attribution(
            "Created", "Second User", "2024-07-02 11:00:00 UTC", "https://slack.com/second"
        )
        body = f"""{first_attribution}

# Header

{second_attribution}

This content should remain including the second attribution line."""

        result = parse_issue_or_pr_body(body)
        expected = ParsedIssueOrPRBody(
            cleaned_body=f"""{second_attribution}

This content should remain including the second attribution line.""",
            opened_by="First User",
            slack_message_url="https://slack.com/first",
            created_date="2024-07-01 10:00:00 UTC",
        )
        assert result == expected

    def test_complex_slack_url(self):
        """Test parsing a complex Slack URL with query parameters."""
        attribution = format_attribution(
            "Created",
            "Emma Thompson",
            "2024-08-12 16:45:30 UTC",
            "https://workspace.slack.com/archives/C1234567890/p1723481130?thread_ts=1723480000.123456&cid=C1234567890",
        )
        body = f"""{attribution}

# Complex Request

Need complex analysis."""

        result = parse_issue_or_pr_body(body)
        expected = ParsedIssueOrPRBody(
            cleaned_body="Need complex analysis.",
            opened_by="Emma Thompson",
            slack_message_url="https://workspace.slack.com/archives/C1234567890/p1723481130?thread_ts=1723480000.123456&cid=C1234567890",
            created_date="2024-08-12 16:45:30 UTC",
        )
        assert result == expected

    def test_attribution_format_as_generated_by_api(self):
        """Test the exact format as generated by _create_attribution in bot.py."""
        attribution = format_attribution(
            "Created",
            "Real Name User",
            "2024-09-03 13:22:45 UTC",
            "https://dagster-labs.slack.com/archives/C05ABC123DEF/p1725368565",
        )
        body = f"""{attribution}

# Weekly Sales Analysis

Please analyze the sales data for last week and provide:

## Requirements

1. Total revenue breakdown by product category
2. Comparison with previous week
3. Identification of top-performing items

## Data Sources

- Sales database: `sales.weekly_summary`
- Product catalog: `products.categories`

## Deliverables

Dashboard with key metrics and insights."""

        result = parse_issue_or_pr_body(body)
        expected = ParsedIssueOrPRBody(
            cleaned_body="""Please analyze the sales data for last week and provide:

## Requirements

1. Total revenue breakdown by product category
2. Comparison with previous week
3. Identification of top-performing items

## Data Sources

- Sales database: `sales.weekly_summary`
- Product catalog: `products.categories`

## Deliverables

Dashboard with key metrics and insights.""",
            opened_by="Real Name User",
            slack_message_url="https://dagster-labs.slack.com/archives/C05ABC123DEF/p1725368565",
            created_date="2024-09-03 13:22:45 UTC",
        )
        assert result == expected
