name: "Setup Erk Remote Environment"
description: "Consolidated setup for remote workflow execution"

inputs:
  erk-pat:
    description: "ERK_QUEUE_GH_PAT secret"
    required: true
  anthropic-api-key:
    description: "ANTHROPIC_API_KEY secret"
    required: false
  claude-code-oauth-token:
    description: "CLAUDE_CODE_OAUTH_TOKEN secret"
    required: false
  auth-source:
    description: "Name of the env var to use for Claude auth (ANTHROPIC_API_KEY or CLAUDE_CODE_OAUTH_TOKEN)"
    required: false
    default: "ANTHROPIC_API_KEY"

runs:
  using: "composite"
  steps:
    - name: Validate secrets
      shell: bash
      run: |
        if [ -z "${{ inputs.erk-pat }}" ]; then
          echo "::error title=Missing Secret::ERK_QUEUE_GH_PAT not configured"
          exit 1
        fi

        AUTH_SOURCE="${{ inputs.auth-source }}"
        if [ "$AUTH_SOURCE" = "ANTHROPIC_API_KEY" ]; then
          if [ -z "${{ inputs.anthropic-api-key }}" ]; then
            echo "::error title=Missing Secret::ANTHROPIC_API_KEY secret is required (auth-source=$AUTH_SOURCE)"
            exit 1
          fi
        elif [ "$AUTH_SOURCE" = "CLAUDE_CODE_OAUTH_TOKEN" ]; then
          if [ -z "${{ inputs.claude-code-oauth-token }}" ]; then
            echo "::error title=Missing Secret::CLAUDE_CODE_OAUTH_TOKEN secret is required (auth-source=$AUTH_SOURCE)"
            exit 1
          fi
        else
          echo "::error title=Invalid Auth Source::auth-source must be ANTHROPIC_API_KEY or CLAUDE_CODE_OAUTH_TOKEN, got: $AUTH_SOURCE"
          exit 1
        fi

    - name: Export Claude credential
      shell: bash
      run: |
        AUTH_SOURCE="${{ inputs.auth-source }}"
        if [ "$AUTH_SOURCE" = "ANTHROPIC_API_KEY" ]; then
          echo "ANTHROPIC_API_KEY=${{ inputs.anthropic-api-key }}" >> "$GITHUB_ENV"
          echo "Exported ANTHROPIC_API_KEY to environment"
        elif [ "$AUTH_SOURCE" = "CLAUDE_CODE_OAUTH_TOKEN" ]; then
          echo "CLAUDE_CODE_OAUTH_TOKEN=${{ inputs.claude-code-oauth-token }}" >> "$GITHUB_ENV"
          echo "Exported CLAUDE_CODE_OAUTH_TOKEN to environment"
        fi

    - uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.13"

    - uses: ./.github/actions/setup-claude-code

    - name: Install prettier
      shell: bash
      run: npm install -g prettier

    - name: Install erk
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        if [ -d "./packages/erk-shared" ]; then
          uv tool install -e . --with-editable ./packages/erk-shared
        else
          uv sync --group dev
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
        fi

    - name: Validate Claude credentials
      shell: bash
      run: erk exec validate-claude-credentials

    - name: Configure git identity
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
